env1=ForagingRichPoorPatch(interval_time = 3,decision_time=1)
#     # env2=Foraging(interval_time = 3,decision_time=1.4)
#     # env3=Foraging(interval_time = 3,decision_time=0.6)
#     env4=ForagingRichPoorPatch(interval_time = 3,decision_time=random.uniform(0.6,1.4))
    
#     env1.seed(i+50)
#     # env2.seed(i+50)
#     # env3.seed(i+50)
#     env4.seed(i+50)

#     r1,a1,q1=q_learning(env1,1,alpha,epsilon,5000)
#     # r2,a2=q_learning(env2,1,alpha,epsilon,1000)
#     # r3,a3=q_learning(env3,1,alpha,epsilon,1000)
#     r4,a4,q1=q_learning(env4,1,alpha,epsilon,5000)

#     R1.append(r1)
#     # R2.append(r2)
#     # R3.append(r3)
#     R4.append(r4)

# R1=np.array(R1)
# # R2=np.array(R2)
# # R3=np.array(R3)
# R4=np.array(R4)

# a1=np.array(a1)
# # a2=np.array(a2)
# # a3=np.array(a3)
# a4=np.array(a4)

# A1=np.average(R1,axis=0)
# # A2=np.average(R2,axis=0)
# # A3=np.average(R3,axis=0)
# A4=np.average(R4,axis=0)

# # x = np.arange(1000)
# plt.plot(A1, color = 'blue')
# # plt.plot(x,A2, color = 'red')
# # plt.plot(x,A3, color = 'yellow')
# plt.plot(A4, color = 'green')
# plt.legend(["Decision Time = 1", "Decision Time = Uniform(0.6,1.4)"])
# plt.xlabel("Episodes")
# plt.ylabel("Rewards")
# plt.title("Q learning Rewards vs Episodes")
# plt.savefig('Qlearning reward92.pdf')
# plt.close()

# x = np.arange(1000)
# plt.plot(a1, color = 'blue')
# # plt.plot(a2, color = 'red')
# # plt.plot(a3, color = 'yellow')
# plt.plot(a4, color = 'green')
# plt.legend(["Decision Time = 1", "Decision Time = Uniform(0.6,1.4)"])
# plt.xlabel("No of Patches")
# plt.ylabel("Number of harvests")
# plt.title("No of harvests vs Patches")
# plt.savefig('Harvest Rewards92.pdf')
# plt.close()